/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tdyh_android_tdmvp_utils_JNIUtils */

#ifndef _Included_com_tdyh_android_tdmvp_utils_JNIUtils
#define _Included_com_tdyh_android_tdmvp_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tdyh_android_tdmvp_utils_JNIUtils
 * Method:    getPublicKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tdyh_android_tdmvp_utils_JNIUtils_getPublicKey
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
